### ISSUE TITLE
Driver Profiles

### ISSUE THREAD

**Issue by falOn-Dev** [Team2537/2024Crescendo#15]
System for storing driver preferences like cubic vs linear joystick mapping, ramp rates, and axis inversions. Must be capable of integrating with the abstract controller code from Issue #13

**Comment by falOn-Dev** [comment]
Possibly a global `Driver` object that functions as sort of a constants class, that you can load `DriverProfile` objects to?

**Comment by falOn-Dev** [comment]
Works with global `Driver` Object that allows you to get things like inversions and input mapping

**Comment by jstN0body** [comment]
Driver Profiles are completed, Driver object will be added as a separate issue
