### ISSUE TITLE
BoB Pivot Rewrite / Cleanup

### ISSUE THREAD

**Issue by falOn-Dev** [Team2537/2024Crescendo#67]
Pivot needs toe be rewritten and/or cleaned up for Battle o' Baltimore, here are the important features

- Controlled using PID, Feedforward, and Motion Profiling, view [THIS EXAMPLE](https://github.com/REVrobotics/2024-REV-ION-FRC-Starter-Bot/blob/main/src/main/java/frc/robot/subsystems/ArmSubsystem.java) to see how it can be implemented without feedforward, but it needs feedforward
- Have command factories within the subsystem for smaller commands, minimize boilerplate
- Use measures in as many possible locations, with radians as the bast unit for things like feedforward and PID control
- Keep it simple, stupid

I trust your judgement in determining the best ways to implement these.

**Comment by Something-Inconspicuous** [comment]
There are a few places where the units being used are not clearly stated (really just the autoaim map pretty much). Could you please document all intended units that you know of? Thanks.

**Comment by falOn-Dev** [comment]
Added it in, try not to have an aneurism

**Comment by falOn-Dev** [comment]
You should be using the [`Commands`](https://github.wpilib.org/allwpilib/docs/release/java/edu/wpi/first/wpilibj2/command/Commands.html) class for your factories, not creating full classes within the subsystem
